name: "Modpack Suggestion"
description: "Have a new mod to suggest? Find a cool resource pack? Maybe you have an idea for a modpack recipe or item!"
title: "[Suggestion]: "
labels: ["suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this suggestion feedback, it helps Velox grow and improve!     
  - type: dropdown
    attributes:
      label: Type of Suggestion
      description: "What type of suggestion?"
      options:
        - New Datapack
        - New Mod
        - New Modpack Item
        - New Modpack Structure
        - New Recipe
        - New Resourcepack
        - New Shader
      default: 0
    validations:
      required: true
  - type: input
    attributes:
      label: Name of Suggested item
      description: "Name of mod, data pack, resource, or shader with link to Curseforge or Modrinth page."
      placeholder: Shadow Realms
    validations:
      required: true  
  - type: textarea
    attributes:
      label: Explain your idea or suggestion.
      description: "Why it should be included or describe your new recipe or item idea."
      placeholder: It is a good fit because... The modpack needs this recipe...
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running?
      options:
        - 1.20.1 (Velox Resurrected)
        - 1.18.2 (Velox Classic)
      default: 0
    validations:
      required: true
